flowchart TB

    TaskManager

    TaskManager --> UsersModule

    TaskManager --> RolesModule

    TaskManager --> PermissionsModule

    TaskManager --> TasksModule

    TaskManager --> AuditModule
