erDiagram

    USERS {
        bigint user_id PK
        string email
        string pass_hash
        datetime created_at
        boolean is_active
        datetime deleted_at
        bigint deleted_by
    }

    TASKS {
        bigint task_id PK
        string title
        string description
        string status
        boolean is_active
        datetime created_at
        datetime due_at
        datetime deleted_at
        bigint deleted_by
    }

    ROLES {
        bigint role_id PK
        string name
        string description
        datetime created_at
        datetime deleted_at
        bigint deleted_by
        boolean is_active
    }

    PERMISSIONS {
        bigint permission_id PK
        string name
        string description
        datetime created_at
        datetime deleted_at
        bigint deleted_by
        boolean is_active
    }

    AUDIT_LOGS {
        bigint log_id PK
        bigint user_id FK
        string action
        string entity_name
        bigint entity_id
        datetime timestamp
        text old_values
        text new_values
        datetime created_at
        datetime deleted_at
        bigint deleted_by
    }

    USER_ROLES {
        bigint id PK
        bigint user_id FK
        bigint role_id FK
    }

    ROLE_PERMISSIONS {
        bigint id PK
        bigint role_id FK
        bigint permission_id FK
    }

    USER_PERMISSIONS {
        bigint id PK
        bigint user_id FK
        bigint permission_id FK
    }

    TASK_ASSIGNMENT {
        bigint id PK
        bigint user_id FK
        bigint task_id FK
        datetime assigned_at
        string assignment_role
    }

    USERS ||--o{ USER_ROLES : has
    ROLES ||--o{ USER_ROLES : assigned_to

    ROLES ||--o{ ROLE_PERMISSIONS : grants
    PERMISSIONS ||--o{ ROLE_PERMISSIONS : included_in

    USERS ||--o{ USER_PERMISSIONS : receives
    PERMISSIONS ||--o{ USER_PERMISSIONS : assigned

    USERS ||--o{ TASK_ASSIGNMENT : participates
    TASKS ||--o{ TASK_ASSIGNMENT : contains

    USERS ||--o{ AUDIT_LOGS : generates